XDG compatibility
Jguer/yay pull request #1485
Opened 2021-04-12 03:21 UTC by keeganjk

This makes it so that someone with a different cache configuration than ~/.cache can have things cached in their custom directory.

2021-04-12 14:22 UTC, Jguer requested changes
If `$XDG_CACHE_HOME` is not set, build dir and ABSdir seem to get set to root `/yay` and `/yay/abs`

2021-04-12 15:02 UTC, keeganjk commented
I was thinking of possibly also adding a part that would set `$XDG_CACHE_HOME` to `~/.cache` if it was not set.

2021-06-01 19:35 UTC, tengwar commented
> part that would set `$XDG_CACHE_HOME` to `~/.cache` if it was not set

According to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables), if `$XDG_CACHE_HOME` is not set, a default value of `$HOME/.cache` should be used. I believe you meant just that, but it kind of sounds like you want to set the envvar instead of using a default, so I'm clarifying just in case.

2021-06-03 15:18 UTC, keeganjk commented
> > part that would set `$XDG_CACHE_HOME` to `~/.cache` if it was not set
> 
> According to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables), if `$XDG_CACHE_HOME` is not set (or empty), a default value of `$HOME/.cache` should be used. I believe you meant just that, but it kind of sounds like you want to set the envvar instead of using a default, so I'm clarifying just in case.

Yes, if `$XDG_CACHE_HOME` is not set, it should use the default, `~/.cache`.

2021-07-25 09:36 UTC, Jguer commented
@keeganjk are you still working on this?

2021-08-02 20:06 UTC, keeganjk commented
> @keeganjk are you still working on this?

No, I am not currently working on this.

2021-09-04 23:34 UTC, Jguer commented
Closing as this is already implemented by `NewConfig` , `getCacheHome`

2021-09-04 23:34 UTC, closed without merging