Fix ContinueTask user prompt for locales with uppercase yes
Jguer/yay pull request #1735
Opened 2022-03-27 12:10 UTC by Drumstickx

This pull request fixes the issue outlined in ContinueTask #1726.

2022-03-28 15:21 UTC, Drumstickx commented
Also fixes #1737

2022-03-29 08:45 UTC, Jguer commented
well spotted, that seems to be the issue indeed, thanks, I'll probably make a release soon, just unsure between making a patch only for this or a major including the new sort algorithm

2022-03-29 16:09 UTC, Jguer requested changes

2022-03-29 16:09 UTC, Jguer commented on pkg/text/text.go
>  	response = strings.ToLower(response)
In this case you should not need the ToLower if you're using `strings.EqualFold`, at least from checking the documentation

2022-03-29 16:43 UTC, Drumstickx commented on pkg/text/text.go
>  	response = strings.ToLower(response)
Correct, I missed that when fixing the linter violation. Thanks for the hint.

2022-03-30 07:39 UTC, Jguer approved these changes

2022-03-31 12:19 UTC, merged