Fixes syntax error #2506
Jguer/yay pull request #2507
Opened 2024-09-17 18:18 UTC by tijko

https://github.com/Jguer/yay/issues/2506

2024-09-17 19:29 UTC, radiooperator-19 requested changes
Do not remove quotation marks; just use `\"` like other .po files

2024-09-18 04:08 UTC, tijko commented
> Do not remove quotation marks; just use `\"` like other .po files

I actually did that in my original change but reverted when I noticed in [en.po](https://github.com/Jguer/yay/blob/84d8f1b7b3bc7448f24abd57f48ff0e9dfbdb388/po/en.po#L372)

2024-09-18 05:29 UTC, radiooperator-19 approved these changes

2024-09-18 07:43 UTC, Jguer approved these changes
seems there's an issue with xgotext, I will check out what's happening there

2024-09-18 07:46 UTC, merged